// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB36Y69vIIfhuH6v3vHYaz47bmQ6Yp_KwU',
    appId: '1:842624631465:web:f7c9b7f3691fa729d65fb8',
    messagingSenderId: '842624631465',
    projectId: 'conferencia-app',
    authDomain: 'conferencia-app.firebaseapp.com',
    storageBucket: 'conferencia-app.appspot.com',
    measurementId: 'G-PLPYV4JD0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5mWG2x19UGWNmaZH8cqBba9VekGCzHRU',
    appId: '1:842624631465:android:9b5e92037b0da473d65fb8',
    messagingSenderId: '842624631465',
    projectId: 'conferencia-app',
    storageBucket: 'conferencia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1HYivDbHZL_X-LZbfhEZi2twmMsnwYnA',
    appId: '1:842624631465:ios:a35f8e9d05daab9fd65fb8',
    messagingSenderId: '842624631465',
    projectId: 'conferencia-app',
    storageBucket: 'conferencia-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1HYivDbHZL_X-LZbfhEZi2twmMsnwYnA',
    appId: '1:842624631465:ios:a35f8e9d05daab9fd65fb8',
    messagingSenderId: '842624631465',
    projectId: 'conferencia-app',
    storageBucket: 'conferencia-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB36Y69vIIfhuH6v3vHYaz47bmQ6Yp_KwU',
    appId: '1:842624631465:web:dc9bba9e357a1317d65fb8',
    messagingSenderId: '842624631465',
    projectId: 'conferencia-app',
    authDomain: 'conferencia-app.firebaseapp.com',
    storageBucket: 'conferencia-app.appspot.com',
    measurementId: 'G-HSHRL1RQHD',
  );
}
